const flightlists = [
  {
    id: 1,
    flightNumber: "AV439",
    departure: "New York",
    arrival: "Los Angeles",
    date: "2023-03-04",
    time: "10:00 AM",
    airline: "American Airlines",
  },
  {
    id: 2,
    flightNumber: "DL456",
    departure: "Chicago",
    arrival: "Miami",
    date: "2023-10-02",
    time: "2:00 PM",
    airline: "Delta Airlines",
  },
  {
    id: 3,
    flightNumber: "UA789",
    departure: "San Francisco",
    arrival: "Seattle",
    date: "2023-10-03",
    time: "5:00 PM",
    airline: "United Airlines",
  },
  {
    id: 4,
    flightNumber: "SW101",
    departure: "Las Vegas",
    arrival: "Denver",
    date: "2023-10-04",
    time: "8:00 AM",
    airline: "Southwest Airlines",
  },
  {
    id: 5,
    flightNumber: "BA202",
    departure: "London",
    arrival: "New York",
    date: "2023-10-05",
    time: "12:00 PM",
    airline: "British Airways",
  },
  {
    id: 6,
    flightNumber: "AF303",
    departure: "Paris",
    arrival: "Tokyo",
    date: "2023-10-06",
    time: "3:00 PM",
    airline: "Air France",
  },
  {
    id: 7,
    flightNumber: "LH404",
    departure: "Frankfurt",
    arrival: "Toronto",
    date: "2023-10-07",
    time: "6:00 PM",
    airline: "Lufthansa",
  },
  {
    id: 8,
    flightNumber: "EK505",
    departure: "Dubai",
    arrival: "Sydney",
    date: "2023-10-08",
    time: "9:00 AM",
    airline: "Emirates",
  },
  {
    id: 9,
    flightNumber: "QF606",
    departure: "Sydney",
    arrival: "Auckland",
    date: "2023-10-09",
    time: "11:00 AM",
    airline: "Qantas",
  },
  {
    id: 10,
    flightNumber: "JL707",
    departure: "Tokyo",
    arrival: "Seoul",
    date: "2023-10-10",
    time: "1:00 PM",
    airline: "Japan Airlines",
  },
  {
    id: 11,
    flightNumber: "AC808",
    departure: "Toronto",
    arrival: "Vancouver",
    date: "2023-10-11",
    time: "4:00 PM",
    airline: "Air Canada",
  },
  {
    id: 12,
    flightNumber: "CX909",
    departure: "Hong Kong",
    arrival: "Singapore",
    date: "2023-10-12",
    time: "7:00 PM",
    airline: "Cathay Pacific",
  },
  {
    id: 13,
    flightNumber: "SQ1010",
    departure: "Singapore",
    arrival: "Bangkok",
    date: "2023-10-13",
    time: "10:00 AM",
    airline: "Singapore Airlines",
  },
  {
    id: 14,
    flightNumber: "TK1111",
    departure: "Istanbul",
    arrival: "Rome",
    date: "2023-10-14",
    time: "2:00 PM",
    airline: "Turkish Airlines",
  },
  {
    id: 15,
    flightNumber: "KL1212",
    departure: "Amsterdam",
    arrival: "Barcelona",
    date: "2023-10-15",
    time: "5:00 PM",
    airline: "KLM Royal Dutch Airlines",
  },
  {
    id: 16,
    flightNumber: "VS1313",
    departure: "London",
    arrival: "Los Angeles",
    date: "2023-10-16",
    time: "8:00 AM",
    airline: "Virgin Atlantic",
  },
  {
    id: 17,
    flightNumber: "NZ1414",
    departure: "Auckland",
    arrival: "Wellington",
    date: "2023-10-17",
    time: "12:00 PM",
    airline: "Air New Zealand",
  },
  {
    id: 18,
    flightNumber: "FI1515",
    departure: "Reykjavik",
    arrival: "New York",
    date: "2023-10-18",
    time: "3:00 PM",
    airline: "Icelandair",
  },
  {
    id: 19,
    flightNumber: "AY1616",
    departure: "Helsinki",
    arrival: "Oslo",
    date: "2023-10-19",
    time: "6:00 PM",
    airline: "Finnair",
  },
  {
    id: 20,
    flightNumber: "LH1717",
    departure: "Munich",
    arrival: "Zurich",
    date: "2023-10-20",
    time: "9:00 AM",
    airline: "Lufthansa",
  },
  {
    id: 21,
    flightNumber: "QR1818",
    departure: "Doha",
    arrival: "Dubai",
    date: "2023-10-21",
    time: "11:00 AM",
    airline: "Qatar Airways",
  },
  {
    id: 22,
    flightNumber: "EY1919",
    departure: "Abu Dhabi",
    arrival: "Cairo",
    date: "2023-10-22",
    time: "1:00 PM",
    airline: "Etihad Airways",
  },
  {
    id: 23,
    flightNumber: "JL2020",
    departure: "Tokyo",
    arrival: "Shanghai",
    date: "2023-10-23",
    time: "4:00 PM",
    airline: "Japan Airlines",
  },
  {
    id: 24,
    flightNumber: "TG2121",
    departure: "Bangkok",
    arrival: "Phuket",
    date: "2023-10-24",
    time: "7:00 PM",
    airline: "Thai Airways",
  },
  {
    id: 25,
    flightNumber: "MH2222",
    departure: "Kuala Lumpur",
    arrival: "Singapore",
    date: "2023-10-25",
    time: "10:00 AM",
    airline: "Malaysia Airlines",
  },

  {
    id: 26,
    flightNumber: "CI2323",
    departure: "Taipei",
    arrival: "Tokyo",
    date: "2023-10-26",
    time: "2:00 PM",
    airline: "China Airlines",
  },
  {
    id: 27,
    flightNumber: "PR2424",
    departure: "Manila",
    arrival: "Hong Kong",
    date: "2023-10-27",
    time: "5:00 PM",
    airline: "Philippine Airlines",
  },
  {
    id: 28,
    flightNumber: "VN2525",
    departure: "Hanoi",
    arrival: "Ho Chi Minh City",
    date: "2023-10-28",
    time: "8:00 AM",
    airline: "Vietnam Airlines",
  },
  {
    id: 29,
    flightNumber: "JL2626",
    departure: "Tokyo",
    arrival: "Seoul",
    date: "2023-10-29",
    time: "12:00 PM",
    airline: "Japan Airlines",
  },
  {
    id: 30,
    flightNumber: "NH2727",
    departure: "Tokyo",
    arrival: "Osaka",
    date: "2023-10-30",
    time: "3:00 PM",
    airline: "All Nippon Airways",
  },
];

module.exports = flightlists;
